<?php

/**
 * @file
 * 
 *  Agence Web
 *  Fichier principal du module
 *
 * @package AgenceWeb
 *
 * @author
 *  Papa Pathe SENE
 *  
 * @copyright
 *  Xarala Web Studios
 * 
 */

/**
 * Implements hook_menu().
 */
function agence_web_menu() {

  /**
   * Declare an array of menu items to load
   * @var array
   */
  $items = array();


  $items['admin/agence-web'] = array(
    'title' => 'Agence WEB',
    'description' => 'Manage your web agency: clients, projects, invoices.',
    'access arguments' => array('manage web agency'),
    'page callback' => 'system_admin_menu_block_page',
    'file' => 'system.admin.inc',
    'file path' => drupal_get_path('module', 'system'),
  );

  $items['admin/agence-web/accueil'] = array(
    'title' => 'accueil',
    'description' => 'gestion agence web',
    'page callback' => 'agence_web_home_page',
    'access arguments' => array('manage agence web clients'),
    'file' => 'core.inc.php',
    'file path' => drupal_get_path('module', 'agence_web'),
    'type' => MENU_DEFAULT_LOCAL_TASK,
  );

  /**
   * Element de menu pour créer une section dans la page de configuration de Drupal
   */
  $items['admin/config/agence-web'] = array(
    'title' => 'Agence Web',
    'description' => 'Configurez votre agence web',
    'page callback' => 'system_admin_menu_block_page',
    'access arguments' => array('configure agence web'),
    'position' => 'left',
    'weight' => -10,
    'file' => 'system.admin.inc',
    'file path' => drupal_get_path('module', 'system'),
  );

  $items['admin/config/agence-web/defauts'] = array(
    'title' => 'Paramètres par défaut.',
    'description' => 'Paramètres par défaut du module agence web.',
    'access arguments' => array('configure agence web'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('agence_web_config'),
    'weight' => -11,
  );


  /**
   * return the array we build above
   */
  return $items;
}

/**
 * Fonction de configuration du module.
 *
 * @return Array 
 *
 * Retourne un tableau contenant un formulaire drupal
 *
 * @todo créer le formulaire de configuration drupal
 */
function agence_web_config() {
  $content =  array(
    'raw_markup' => array(
      '#type' => 'markup', 
      '#content' => '<h2>Agence WEB</h2><p>Configurer votre agence web.</p>'
    )
  );
  return $content;
}