<?php 


include 'agence_web_clients.permissions';

/**
 * @file
 * 
 *  Agence Web
 *  Fichier principal du module
 *
 * @author
 *  Papa Pathe SENE
 *  
 * @copyright
 *  Xarala Web Studios
 * 
 */


/**
 * Implements hook_menu().
 */
function agence_web_clients_menu() {
  
  $items = array();

  $items['admin/agence-web/clients'] = array (
    'title'            => t('Clients'),
    'description'      => t('gestion des clients'),
    'page callback'    => 'agence_web_gestion_clients',
    'access arguments' => array (AGENCE_WEB_CLIENTS_PERMISSION_DE_GERER),
    'file'             => 'agence_web_clients.admin.inc',
    'file path'        => drupal_get_path('module', 'agence_web_clients'),
  );


  $items['admin/agence-web/clients/nouveau'] = array (
    'title'            => t('nouveau client'),
    'description'      => t('Créer un client'),
    'page callback'    => 'drupal_get_form',
    'page arguments'   => array('agence_web_clients_formulaire_creation'),
    'access arguments' => array (AGENCE_WEB_CLIENTS_PERMISSION_DE_CREER_CLIENT),
    'type'             => MENU_LOCAL_ACTION,
    'file'             => 'agence_web_clients.admin.inc',
    'file path'        => drupal_get_path('module', 'agence_web_clients')
  );

  $items['admin/agence-web/clients/clients-a-recouvrer'] = array (
    'title'            => t('Clients à recouvrer'),
    'description'      => t('Voir les clients à recouvrer'),
    'page callback'    => 'agence_web_clients_a_recouvrer',
    'access arguments' => array ('view clients to bill'),
    'type'             => MENU_LOCAL_ACTION,
    'file'             => 'agence_web_clients.admin.inc',
    'file path'        => drupal_get_path('module', 'agence_web_clients')
  );

  /**
   * élement de menu pour configurer le module agence_web_clients
   */
  $items['admin/config/system/agence-web-clients'] = array (
    'title'            => t('Clients Agence Web'),
    'description'      => t('Configurez les clients de votre agence web'),
    'page callback'    => 'drupal_get_form',
    'page arguments'   => array('agence_web_clients_formulaire_configuration'),
    'access arguments' => array (AGENCE_WEB_CLIENTS_PERMISSION_DE_CONFIGURER),
    'file'             => 'agence_web_clients.admin.inc',
    'file path'        => drupal_get_path('module', 'agence_web_clients')
  );

  return $items;

}


/**
 * Implements hook_permission().
 * 
 * @return array 
 *  Un tableau associatif avec les permisions définies par le module 
 *  Agence WEB Clients.
 * 
 */
function agence_web_clients_permission() {
  return array(

    AGENCE_WEB_CLIENTS_PERMISSION_DE_GERER =>  array( 
      'title' => t('administrer les clients'),
      'description' => t('administrer les clients de notre agence web'),
    ),

    AGENCE_WEB_CLIENTS_PERMISSION_DE_CREER_CLIENT => array(
      'title'       => t('créer un client'),
      'description' => t('créer un client pour notre agence web')
    ),

    AGENCE_WEB_CLIENTS_PERMISSION_DE_CONFIGURER =>  array( 
      'title' => t('configurer agence web'),
      'description' => t('configurer les clients de notre agence web'),
    ),

  );
}





