<?php 


include 'agence_web_clients.permissions';

/**
 * @file
 * 
 *  Agence Web
 *  Fichier principal du module
 *
 * @package AgenceWeb
 *
 * @author
 *  Papa Pathe SENE
 *  
 * @copyright
 *  Xarala Web Studios
 * 
 */


/**
 * Implements hook_menu().
 */
function agence_web_clients_menu() {
  
  $items = array();

  $items['admin/agence-web/clients'] = array(
    'title'            => t('Clients'),
    'description'      => t('gestion des clients'),
    'page callback'    => 'agence_web_gestion_clients',
    'access arguments' => array (AGENCE_WEB_CLIENTS_PERMISSION_DE_GERER),
    'file'             => 'agence_web_clients.admin.inc',
    'file path'        => drupal_get_path('module', 'agence_web_clients'),
  );

  $items['admin/agence-web/clients/gerer'] = array(
    'title'            => t('Clients'),
    'description'      => t('gestion des clients'),
    'page callback'    => 'agence_web_gestion_clients',
    'access arguments' => array (AGENCE_WEB_CLIENTS_PERMISSION_DE_GERER),
    'file'             => 'agence_web_clients.admin.inc',
    'file path'        => drupal_get_path('module', 'agence_web_clients'),
    'type'             => MENU_DEFAULT_LOCAL_TASK,
  );

  $items['admin/agence-web/clients/%'] = array(
    'title'            => t('Détails du client'),
    'description'      => t('affichage détaillé des clients'),
    'page callback'    => 'agence_web_details_client',
    'page arguments'   => array(3),
    'access arguments' => array (AGENCE_WEB_CLIENTS_PERMISSION_DE_VISUALISER_CLIENT),
    'file'             => 'agence_web_clients.admin.inc',
    'file path'        => drupal_get_path('module', 'agence_web_clients'),
  );

  $items['admin/agence-web/clients/%/details'] = array(
    'title'            => t('Détails du client'),
    'description'      => t('affichage détaillé des clients'),
    'page callback'    => 'agence_web_details_client',
    'page arguments'   => array(3),
    'access arguments' => array (AGENCE_WEB_CLIENTS_PERMISSION_DE_VISUALISER_CLIENT),
    'file'             => 'agence_web_clients.admin.inc',
    'file path'        => drupal_get_path('module', 'agence_web_clients'),
    'type'             => MENU_DEFAULT_LOCAL_TASK
  );

  $items['admin/agence-web/clients/%/modifier'] = array(
    'title'            => t('modifier'),
    'description'      => t('modifier ce client'),
    'page callback'    => 'agence_web_modifier_client',
    'page arguments'   => array(3),
    'access arguments' => array (AGENCE_WEB_CLIENTS_PERMISSION_DE_VISUALISER_CLIENT),
    'file'             => 'agence_web_clients.admin.inc',
    'file path'        => drupal_get_path('module', 'agence_web_clients'),
    'type'             => MENU_LOCAL_TASK,
  );

  $items['admin/agence-web/clients/%/supprimer'] = array(
    'title'            => t('supprimer'),
    'description'      => t('supprimer ce client'),
    'page callback'    => 'agence_web_supprimer_client',
    'page arguments'   => array(3),
    'access arguments' => array (AGENCE_WEB_CLIENTS_PERMISSION_DE_SUPPRIMER_CLIENT),
    'file'             => 'agence_web_clients.admin.inc',
    'file path'        => drupal_get_path('module', 'agence_web_clients'),
    'type'             => MENU_CALLBACK,
  );  

  $items['admin/agence-web/clients/%/projets'] = array(
    'title'            => t('projets'),
    'description'      => t('afficher les projets soumis par ce client'),
    'page callback'    => 'agence_web_projets_client',
    'page arguments'   => array(3),
    'access arguments' => array (AGENCE_WEB_CLIENTS_PERMISSION_DE_VISUALISER_CLIENT),
    'file'             => 'agence_web_clients.admin.inc',
    'file path'        => drupal_get_path('module', 'agence_web_clients'),
    'type'             => MENU_LOCAL_TASK,
  );

  $items['admin/agence-web/clients/nouveau'] = array(
    'title'            => t('NOUVEAU CLIENT'),
    'description'      => t('Créer un client'),
    'page callback'    => 'drupal_get_form',
    'page arguments'   => array('agence_web_clients_formulaire_creation'),
    'access arguments' => array (AGENCE_WEB_CLIENTS_PERMISSION_DE_CREER_CLIENT),
    'type'             => MENU_LOCAL_TASK,
    'file'             => 'agence_web_clients.admin.inc',
    'file path'        => drupal_get_path('module', 'agence_web_clients')
  );

  $items['admin/agence-web/clients/clients-a-recouvrer'] = array(
    'title'            => t('CLIENTS A RECOUVRER'),
    'description'      => t('Voir les clients à recouvrer'),
    'page callback'    => 'agence_web_clients_a_recouvrer',
    'access arguments' => array ('view clients to bill'),
    'type'             => MENU_LOCAL_TASK,
    'file'             => 'agence_web_clients.admin.inc',
    'file path'        => drupal_get_path('module', 'agence_web_clients')
  );

  // Configuration
  // ----------------------------------------------------------------------------------------

  /**
   * menu pour configurer le module agence_web_clients
   */
  $items['admin/config/agence-web/clients'] = array(
    'title'            => t('Clients'),
    'description'      => t('Configurez les clients de votre agence web'),
    'page callback'    => 'drupal_get_form',
    'page arguments'   => array('agence_web_clients_formulaire_configuration'),
    'access arguments' => array (AGENCE_WEB_CLIENTS_PERMISSION_DE_CONFIGURER),
    'file'             => 'agence_web_clients.admin.inc',
    'file path'        => drupal_get_path('module', 'agence_web_clients'),
    'weight'           => '-12'
  );

  return $items;

}


/**
 * Implements hook_permission().
 * 
 * @return array 
 *  Un tableau associatif avec les permisions définies par le module 
 *  Agence WEB Clients.
 * 
 */
function agence_web_clients_permission() {
  return array(

    AGENCE_WEB_CLIENTS_PERMISSION_DE_GERER             => array( 
      'title'        => t('Administrer les clients'),
      'description'  => t('Administrer les clients de notre agence web'),
    ),

    AGENCE_WEB_CLIENTS_PERMISSION_DE_CREER_CLIENT      => array(
      'title'        => t('Créer un client'),
      'description'  => t('Créer un client pour notre agence web')
    ),

    AGENCE_WEB_CLIENTS_PERMISSION_DE_CONFIGURER        => array( 
      'title'        => t('Configurer agence web'),
      'description'  => t('configurer les clients de notre agence web'),
    ),

    AGENCE_WEB_CLIENTS_PERMISSION_DE_VISUALISER_CLIENT => array(
      'title'        => t('Visualiser les clients'),
      'description'  => t('Visualiser les clients dans l\'admiistration')
    ),

  );
}





